# Generated by Django 4.0.3 on 2022-03-05 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordOccurences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('keywords', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_text', models.CharField(max_length=200, verbose_name='Search text')),
                ('search_time', models.DateTimeField(verbose_name='Search time')),
                ('search_result', models.JSONField(verbose_name='Search result')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_searched', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
